# Generated by Django 3.0.6 on 2020-06-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20200530_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
