# Generated by Django 3.0.6 on 2020-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_auto_20200601_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
