# Generated by Django 3.0.6 on 2020-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0004_auto_20200602_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
