# Generated by Django 3.0.6 on 2020-06-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0005_auto_20200603_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
