# Generated by Django 2.2.13 on 2020-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0007_auto_20200606_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='exercise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
