# Generated by Django 2.2.13 on 2021-09-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0008_chapter_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='output_file',
            field=models.ImageField(blank=True, null=True, upload_to='output'),
        ),
        migrations.AddField(
            model_name='program',
            name='raptor_file',
            field=models.ImageField(blank=True, null=True, upload_to='raptor'),
        ),
    ]
