# Generated by Django 2.2.13 on 2021-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0009_auto_20210929_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
