# Generated by Django 2.2.13 on 2021-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0010_chapter_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
